---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: false
  fixme:
    enabled: true
  tailor:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.swift"
exclude_paths:
- docs/*
